import numpy as np
import matplotlib.pyplot as plt
from PISC.engine import Krylov_complexity
from PISC.dvr.dvr import DVR1D
from Krylov_WF_tools import coh_st_coeff, fix_vecs, comp_Ot, Cn, av_O, find_coeff_wf, verify_Ct, get_phi_t
import scipy

"""
Given an operator \hat{O} of a system, the time-evolved operator is given by
        \hat{O}(t) = \hat{U}†(t) \hat{O} \hat{U}(t)
where \hat{U}(t) = exp(-i \hat{H} t) is the time-evolution operator generated by the Hamiltonian \hat{H} of the system.

This can be expanded on a Krlyov basis {O_n} as:
        \hat{O}(t) = \sum_n \phi_n(t) \hat{O}_n
The Krylov basis depends on the inner product defined on the operator space and is in general temperature dependent.

In quench experiments, one is interested in computing the expectation value of the time-evolved operator in a given initial state |psi>:
        <psi| \hat{O}(t) |psi> = \sum_n \phi_n(t) <psi| \hat{O}_n |psi> := \sum_n \phi_n(t) W_n
where W_n are the so-called "wavefunction coefficients".

In this code, we compute and plot the wavefunction coefficients W_n for a 1D box of length L with hard-wall boundary conditions.
"""

xl_fs = 16 
yl_fs = 16
tp_fs = 12
le_fs = 13#9.5

def compute_Wn(O, coeffs, vals, bn):
    Wn = np.zeros(len(bn)) + 0j
    neigs = len(vals)

    O_m1 = np.zeros((neigs, neigs), dtype=complex)
    O_n = O.copy()
    O_p1 = np.zeros((neigs, neigs), dtype=complex)

    for n in range(len(bn)-1):
        b_n = bn[n]
        b_p1 = bn[n+1] 
        for j in range(neigs):
            for k in range(neigs):
                temp =  np.conj(coeffs[j])*coeffs[k]*O_n[j, k]
                print('n={}, j={}, k={}, temp={}'.format(n, j, k, O_n[j, k]))
                Wn[n] += temp
                Ej = vals[j]
                Ek = vals[k]
                O_p1[j, k] = ((Ej-Ek)*O_n[j, k] - b_n*O_m1[j, k]) / b_p1
                if(b_p1 < 1e-3):
                    print('b_p1 is zero at n={}, breaking loop'.format(n))
        print('Wn[{}] = {}'.format(n, Wn[n]))
        O_m1 = O_n.copy()
        O_n = O_p1.copy()
        
 
    print('Wn[{}] = {}'.format(len(bn)-1, Wn[-1]))
    return Wn

ngrid = 1000

Len = 4.0 # 0.37*4

lb = -Len/2
ub = Len/2

m = 0.5 

def potential(x):
    if(x<lb or x>ub):
        return 1e12
    else:
        return 0.0

neigs = 50
potential = np.vectorize(potential)

DVR = DVR1D(ngrid, lb, ub, m, potential)
vals,vecs = DVR.Diagonalize(neig_total=neigs)

print('vecs', vecs.shape)

vecs = fix_vecs(vecs, tol=1e-3)

x_arr = DVR.grid[1:ngrid]
dx = x_arr[1]-x_arr[0]

def pos_mat_anal(neigs, m, L):
    pos_mat_anal = np.zeros((neigs,neigs))
    for i in range(neigs):
        for j in range(neigs):
            if(i==j):
                pos_mat_anal[i,j] = L/2 -   L/2
            else:
                pos_mat_anal[i,j] = L*(1/(i+j+2)**2 - 1/(i-j)**2)*(1-(-1)**(i+j+2))/np.pi**2 
    return pos_mat_anal

vals_anal = np.arange(1,neigs+1)**2*np.pi**2/(2*m*Len**2)
vecs_anal = np.zeros((ngrid-1,neigs))
for i in range(neigs):
    #vecs_anal[:,i] = np.sqrt(2/Len)*np.sin((i+1)*np.pi*x_arr/Len)
    vecs_anal[:,i] = np.sqrt(2/Len)*np.sin((i+1)*np.pi*(x_arr+Len/2)/Len)

if(0):
    O = pos_mat_anal(neigs, m, Len)
    vecs = vecs_anal
    vals = vals_anal
    
    pos_mat = np.zeros((neigs,neigs))
    pos_mat = Krylov_complexity.krylov_complexity.compute_pos_matrix(vecs, x_arr, dx, dx, pos_mat)
    
else:
    pos_mat = np.zeros((neigs,neigs))
    pos_mat = Krylov_complexity.krylov_complexity.compute_pos_matrix(vecs, x_arr, dx, dx, pos_mat)
    O = (pos_mat)

potkey = 'L_{}_m_{}_1DB'.format(Len,m)

if(0): #Use Eigenstates
    n_wf = 10
    wf = vecs[:,n_wf]  # ground state wavefunction
    
    coeff_wf = np.zeros(neigs)
    #coeff_wf[n_wf] = 1.0  # initial state is the ground state
    
    coeff_wf[:n_wf] = 1.0/np.sqrt(n_wf)  # initial state is equal superposition of first n_wf eigenstates

liou_mat = np.zeros((neigs,neigs))
L = Krylov_complexity.krylov_complexity.compute_liouville_matrix(vals,liou_mat)

LO = np.zeros((neigs,neigs))
LO = Krylov_complexity.krylov_complexity.compute_hadamard_product(L,O,LO)

ncoeff = 200
barr = np.zeros(ncoeff)

x0 = 0.0
p0 = 1.0
sigma_x = 1.0 #0.25

coeff_wf, wf = coh_st_coeff(x0, p0, sigma_x, x_arr, vecs, neigs)
#print('coeff_wf', coeff_wf[:10])


T = 1.0
beta = 1/T

ipkey = 'wgm'#'dir'

ip = 0.0
ip = Krylov_complexity.krylov_complexity.compute_ip(O, O, beta, vals, 0.5, ip, ipkey)
print('ip(O,O)', ip)
O/=np.sqrt(ip)
ip = Krylov_complexity.krylov_complexity.compute_ip(O, O, beta, vals, 0.5, 0.0, ipkey)
print('ip(O,O) after normalization', ip)

barr = np.zeros(ncoeff)
#barr = Krylov_complexity.krylov_complexity.compute_lanczos_coeffs(O, L, barr, beta, vals, 0.5, 'wgm')

Warr = np.zeros(ncoeff, dtype=complex)
barr, Warr = Krylov_complexity.krylov_complexity.compute_lanczos_coeffs_wf(O, L, barr, beta, vals, 0.5, ipkey, Warr, coeff_wf)

if(1):
    print('m', m, 'Len', Len)
    print('vals', vals[:10], np.pi**2/(2*m*Len**2)) 
    
    n=20
    m=20
    On = np.zeros((neigs, neigs), dtype=complex)
    Om = np.zeros((neigs, neigs), dtype=complex)
    bnarr = np.zeros(ncoeff)
    bmarr = np.zeros(ncoeff)
    
    #O[:] = 1.0 + np.random.normal(0, 1, size=O.shape)  #Test with random operator
    bnarr, On = Krylov_complexity.krylov_complexity.compute_on_matrix(O, L, bnarr, beta, vals, 0.5, 'wgm', On, n+1)
    bmarr, Om = Krylov_complexity.krylov_complexity.compute_on_matrix(O, L, bmarr, beta, vals, 0.5, 'wgm', Om, m+1)

    ip_nm = 0.0
    ip_nm = Krylov_complexity.krylov_complexity.compute_ip(On/bnarr[n], Om/bmarr[m], beta, vals, 0.5, ip_nm, 'wgm')
    print('Inner product <O_n|O_m> with n={} m={} : {}'.format(n, m, ip_nm))

    On_cross = On[1::2,10] #int(neigs/4)]
    print('On_cross', np.around(On_cross,3)[:20])
    plt.plot(np.log(np.abs(On_cross)), label=' n={}'.format(n))
    plt.xlabel('Index', fontsize=xl_fs)
    plt.ylabel('|O_n| cross section', fontsize=yl_fs)
    plt.legend(fontsize=le_fs)
    
    #plt.imshow(np.log(np.abs(On)))
    #plt.colorbar()
    #plt.title('|O_n| with n={}'.format(n))
    plt.show()
    exit()

if(1):
    #barr+= np.random.normal(0, 10, size=ncoeff)  #Add small noise to lanczos coeffs to test verification
    plt.plot(barr, marker='o')
    plt.xlabel('n')
    plt.ylabel('$b_n$')
    plt.title('Lanczos Coefficients for {}'.format(potkey))
    plt.show()

    tarr = np.arange(0.0, 100.0, 0.1)
    verify_Ct(O, vals, barr, beta, neigs, tarr, ip='wgm')
    exit()  

#Wn = compute_Wn(O, coeff_wf, vals, barr)

if(1): #Verify if Wn is correct by reconstructing <psi|O|psi>
    Wn = Warr.copy()
    if(1):
        plt.plot(Wn.real, marker='o', label='Wn Real')
        #plt.plot(Wn.imag, marker='x', label='Wn Imag')
        #plt.ylim([-5,5])
        plt.xlabel('n')
        plt.ylabel('Wn')
        plt.title('Wavefunction Coefficients Wn for {}'.format(potkey))
        plt.legend()
        plt.show()

    tarr = np.arange(0.0, 10.0, 0.01)
    verify_Ct(O, vals, barr, beta, neigs, tarr, ip=ipkey)
    
    phi_t = get_phi_t(barr, tarr)
    
    #Expectation value directly
    exp_t_dir = np.zeros(len(tarr), dtype=complex)
    for i in range(neigs):
        for j in range(neigs):
            exp_t_dir += np.conj(coeff_wf[i])*coeff_wf[j]*O[i,j]*np.exp(1j*(vals[i]-vals[j])*tarr)
    

    exp_t_Wn = np.zeros(len(tarr), dtype=complex)
    for i in range(len(tarr)):
        for n in range(len(Wn)):
            exp_t_Wn[i] += Wn[n]*phi_t[i,n]*(1j)**n

    plt.plot(tarr, exp_t_dir.real, label='Direct Real')
    plt.plot(tarr, exp_t_Wn.real, '--', label='Wn Real')
    plt.ylim([exp_t_dir.real.min()*1.1, exp_t_dir.real.max()*1.1])
    plt.xlabel('Time')
    plt.ylabel('Expectation Value ⟨O(t)⟩')
    plt.legend()
    plt.title('Expectation Value Comparison')
    plt.show()

    exit()



plt.plot(np.log(np.abs(Wn)**2), marker='o')

#Fit line to log(|Wn|) to extract decay rate
n_vals = np.arange(len(Wn))
log_Wn = np.log(np.abs(Wn)**2)
coeffs = np.polyfit(n_vals, log_Wn, 1)
decay_rate = -coeffs[0]
print('Decay rate of |Wn|:', decay_rate)
plt.plot(n_vals, np.polyval(coeffs, n_vals), '--', label='Fit: decay rate={:.4f}'.format(decay_rate))



#plt.yscale('log')
plt.show()
