import numpy as np
import matplotlib.pyplot as plt
from PISC.engine import Krylov_complexity
from PISC.dvr.dvr import DVR1D
from Krylov_WF_tools import coh_st_coeff, fix_vecs, verify_Ct, get_phi_t
from PISC.potentials import mildly_anharmonic

"""
Given an operator \hat{O} of a system, the time-evolved operator is given by
        \hat{O}(t) = \hat{U}†(t) \hat{O} \hat{U}(t)
where \hat{U}(t) = exp(-i \hat{H} t) is the time-evolution operator generated by the Hamiltonian \hat{H} of the system.

This can be expanded on a Krlyov basis {O_n} as:
        \hat{O}(t) = \sum_n \phi_n(t) \hat{O}_n
The Krylov basis depends on the inner product defined on the operator space and is in general temperature dependent.

In quench experiments, one is interested in computing the expectation value of the time-evolved operator in a given initial state |psi>:
        <psi| \hat{O}(t) |psi> = \sum_n \phi_n(t) <psi| \hat{O}_n |psi> := \sum_n \phi_n(t) W_n
where W_n are the so-called "wavefunction coefficients".

In this code, we compute and plot the wavefunction coefficients W_n for a 1D box of length L with hard-wall boundary conditions.
"""

def compute_Wn(O, coeffs, vals, bn):
    Wn = np.zeros(len(bn)) + 0j
    neigs = len(vals)

    O_m1 = np.zeros((neigs, neigs), dtype=complex)
    O_n = O.copy()
    O_p1 = np.zeros((neigs, neigs), dtype=complex)

    for n in range(len(bn)-1):
        print('n=', n)
        b_n = bn[n]
        b_p1 = bn[n+1]

        for j in range(neigs):
            for k in range(neigs):
                Wn[n] += np.conj(coeffs[j])*coeffs[k]*O_n[j, k]     
                Ej = vals[j]
                Ek = vals[k]
                if(b_p1 != 0):
                    O_p1[j, k] = ((Ej-Ek)*O_n[j, k] - b_n*O_m1[j, k]) / b_p1
                else:
                    #End the loop if b_p1 is zero
                    O_p1[j, k] = 0.0
                    break
        print('Wn[{}] = {}'.format(n, Wn[n]))
        O_m1 = O_n.copy()
        O_n = O_p1.copy()
        O_p1 = np.zeros((neigs, neigs), dtype=complex)

    for j in range(neigs):
        for k in range(neigs):
            Wn[-1] += np.conj(coeffs[j])*coeffs[k]*O_n[j, k]
    print('Wn[{}] = {}'.format(len(bn)-1, Wn[-1]))
    return Wn

ngrid = 1000

Len = 20

lb = -Len
ub = Len

a = 0.0
b = 0.5
omega = 1.0
m = 1.0
n_anharm = 4
pes = mildly_anharmonic(m,a,b,w=omega,n=n_anharm)

if(0):  # Plot the potential
    xgrid = np.linspace(lb,ub,ngrid)
    plt.plot(xgrid, pes.potential_func(xgrid))
    plt.xlabel('x')
    plt.ylabel('V(x)')
    plt.title('Mildly Anharmonic Potential')
    plt.grid()  
    plt.show()
    exit()


def pos_mat_anal(neigs, m, omega):
    print('m, omega in anal pos mat:', m, omega)
    pos_mat = np.zeros((neigs,neigs))
    for i in range(neigs):
        for j in range(neigs):
            if(i-j==1):
                pos_mat[i,j] = np.sqrt(1/(2*m*omega))*np.sqrt(j+1)
            elif(j-i==1):
                pos_mat[i,j] = np.sqrt(1/(2*m*omega))*np.sqrt(i+1)
            
    return pos_mat

potkey = 'L_{}_MAH_w_{}_a_{}_b_{}_n_{}'.format(Len,omega,a,b,n_anharm)

DVR = DVR1D(ngrid,lb,ub,m,pes.potential_func)
neigs = 100
vals,vecs = DVR.Diagonalize(neig_total=neigs)

vecs = fix_vecs(vecs)

x_arr = DVR.grid[1:ngrid]
dx = x_arr[1]-x_arr[0]

pos_mat = np.zeros((neigs,neigs))
pos_mat = Krylov_complexity.krylov_complexity.compute_pos_matrix(vecs, x_arr, dx, dx, pos_mat)

#pos_mat_analytical = pos_mat_anal(neigs, m, omega)
#pos_mat_diff = pos_mat_analytical - pos_mat

O = pos_mat

liou_mat = np.zeros((neigs,neigs))
L = Krylov_complexity.krylov_complexity.compute_liouville_matrix(vals,liou_mat)

LO = np.zeros((neigs,neigs))
LO = Krylov_complexity.krylov_complexity.compute_hadamard_product(L,O,LO)

ncoeff = 200
barr = np.zeros(ncoeff)

x0 = 1.0
p0 = 0.0
sigma_x = 2.0 #0.25

coeff_wf, wf = coh_st_coeff(x0, p0, sigma_x, x_arr, vecs, neigs)

T = 3.0
beta = 1/T

ip = 0.0
ip = Krylov_complexity.krylov_complexity.compute_ip(O, O, beta, vals, 0.5, ip, 'wgm')
print('ip(O,O)', ip)
O/=np.sqrt(ip)
ip = Krylov_complexity.krylov_complexity.compute_ip(O, O, beta, vals, 0.5, 0.0, 'wgm')

barr = np.zeros(ncoeff)
barr = Krylov_complexity.krylov_complexity.compute_lanczos_coeffs(O, L, barr, beta, vals,0.5, 'wgm')

Wn = compute_Wn(O, coeff_wf, vals, barr)

if(1):
    tarr = np.arange(0.0, 10.0, 0.01)
    phi_t = get_phi_t(barr, tarr)
    print('phi_t shape:', phi_t[0])
    verify_Ct(O, vals, barr, beta, neigs)

    #Expectation value directly
    exp_t_dir = np.zeros(len(tarr), dtype=complex)
    for i in range(neigs):
        for j in range(neigs):
            exp_t_dir += np.conj(coeff_wf[i])*coeff_wf[j]*O[i,j]*np.exp(1j*(vals[i]-vals[j])*tarr)

    exp_t_Wn = np.zeros(len(tarr), dtype=complex)
    for n in range(len(Wn)):
        exp_t_Wn += Wn[n]*phi_t[:,n]*(1j)**n

    plt.plot(tarr, exp_t_dir.real, label='Direct Real')
    plt.plot(tarr, exp_t_Wn.real, '--', label='Wn Real')
    plt.xlabel('Time')
    plt.ylabel('Expectation Value ⟨O(t)⟩')
    plt.legend()
    plt.title('Expectation Value Comparison')
    plt.show()



plt.plot(np.abs(Wn), marker='o')
plt.yscale('log')
plt.show()
